on:
  push:
    branches:
      - main
      - master
      - development

env:
  EXTRA_ARGS: ${{ github.ref == 'refs/heads/development' && '--prerelease' || '' }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Parse package.json
        id: set_var
        run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "packageJson=$content" >> $GITHUB_OUTPUT
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
          echo "${{fromJson(steps.set_var.outputs.packageJson).devDependencies['@wayward/types']}}"

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{fromJson(steps.set_var.outputs.packageJson).devDependencies['@wayward/types']}}" \
              --generate-notes \
              $EXTRA_ARGS
